// <auto-generated />
using AppBug59184;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace AppBug59184.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("AppBug59184.Model.NullableEntity", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("Nullable1");

                    b.Property<long?>("Nullable2");

                    b.Property<long?>("Nullable3");

                    b.Property<long?>("Nullable4");

                    b.HasKey("Key");

                    b.ToTable("NullableEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
